# -*- coding: utf-8 -*-
"""ASP_Integration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c82tZI6BW9jNS9LX_qoAmD1Mbo56iOCW
"""

import joblib

# Load the decision tree model
decision_tree = joblib.load('./model.pkl')

# Define a function to make predictions
def predict_category(input_values):
    # Convert the input values to a list of lists, as the decision tree model expects a 2D array
    input_values = [list(input_values)]

    # Use the loaded decision tree model to make predictions
    predicted_category = decision_tree.predict(input_values)[0]

    # Return the predicted category
    return predicted_category